CREATE DATABASE IF NOT EXISTS `market`;

CREATE TABLE
    IF NOT EXISTS `market`.`cc_ohlcv_spot_1d_raw` (
        `datetime` DATETIME NOT NULL,
        `exchange` VARCHAR(255) NOT NULL,
        `symbol_unmapped` VARCHAR(255) NOT NULL,
        `symbol` VARCHAR(255),
        `base` VARCHAR(255),
        `quote` VARCHAR(255),
        `base_id` BIGINT,
        `quote_id` BIGINT,
        `transform_function` VARCHAR(255),
        `open` DOUBLE,
        `high` DOUBLE,
        `low` DOUBLE,
        `close` DOUBLE,
        `first_trade_timestamp` BIGINT,
        `last_trade_timestamp` BIGINT,
        `first_trade_price` DOUBLE,
        `high_trade_price` DOUBLE,
        `high_trade_timestamp` BIGINT,
        `low_trade_price` DOUBLE,
        `low_trade_timestamp` BIGINT,
        `last_trade_price` DOUBLE,
        `total_trades` BIGINT,
        `total_trades_buy` BIGINT,
        `total_trades_sell` BIGINT,
        `total_trades_unknown` BIGINT,
        `volume` DOUBLE,
        `quote_volume` DOUBLE,
        `volume_buy` DOUBLE,
        `quote_volume_buy` DOUBLE,
        `volume_sell` DOUBLE,
        `quote_volume_sell` DOUBLE,
        `volume_unknown` DOUBLE,
        `quote_volume_unknown` DOUBLE,
        `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        SHARD KEY (`datetime`, `exchange`, `symbol`),
        SORT KEY (`datetime`, `exchange`, `symbol`)
    );

CREATE TABLE
    IF NOT EXISTS `market`.`cc_ohlcv_spot_indices_1d_raw` (
        `unit` VARCHAR(255),
        `datetime` DATETIME NOT NULL,
        `type` VARCHAR(255),
        `market` VARCHAR(255) NOT NULL,
        `asset` VARCHAR(255) NOT NULL,
        `quote` VARCHAR(255),
        `open` DOUBLE,
        `high` DOUBLE,
        `low` DOUBLE,
        `close` DOUBLE,
        `first_message_timestamp` BIGINT,
        `last_message_timestamp` BIGINT,
        `first_message_value` DOUBLE,
        `high_message_value` DOUBLE,
        `high_message_timestamp` BIGINT,
        `low_message_value` DOUBLE,
        `low_message_timestamp` BIGINT,
        `last_message_value` DOUBLE,
        `total_index_updates` BIGINT,
        `volume` DOUBLE,
        `quote_volume` DOUBLE,
        `volume_top_tier` DOUBLE,
        `quote_volume_top_tier` DOUBLE,
        `volume_direct` DOUBLE,
        `quote_volume_direct` DOUBLE,
        `volume_top_tier_direct` DOUBLE,
        `quote_volume_top_tier_direct` DOUBLE,
        `collected_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        SHARD KEY (`datetime`, `market`, `asset`),
        SORT KEY (`datetime`, `market`, `asset`)
    );